dist: trusty
language: node_js
python:
  - '3.6'
node_js:
  - '10'
  - '12'
before_install:
  - sudo rm -f /usr/local/bin/python-config
  - sudo rm -f /usr/local/bin/python
  - sudo ln -s /opt/python/3.6.3/bin/python3-config /usr/local/bin/python-config
  - sudo ln -s /opt/python/3.6.3/bin/python3 /usr/local/bin/python
  - sudo ln -s /opt/python/3.6.3/include/python3.6m /usr/local/include/python3.6m
  - sudo ln -s /opt/python/3.6.3/lib/libpython3.6m.so /usr/local/lib/libpython3.6m.so
  - export LD_LIBRARY_PATH=/opt/python/3.6.3/lib:$LD_LIBRARY_PATH
